name: heursearchilp
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - alsa-lib=1.2.14
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2025.4.26
  - cairo=1.18.4
  - contourpy=1.3.2
  - cpython=3.10.17
  - cycler=0.12.1
  - cyrus-sasl=2.1.27
  - dbus=1.13.6
  - double-conversion=3.3.1
  - expat=2.7.0
  - filelock=3.18.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.58.0
  - freetype=2.13.3
  - fsspec=2025.3.2
  - gmp=6.3.0
  - gmpy2=2.2.1
  - graphite2=1.3.13
  - harfbuzz=11.1.0
  - icu=75.1
  - jinja2=3.1.6
  - keyutils=1.6.1
  - krb5=1.21.3
  - lcms2=2.17
  - ld_impl_linux-64=2.43
  - lerc=4.0.0
  - libabseil=20250127.1
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libclang-cpp20.1=20.1.4
  - libclang13=20.1.4
  - libcups=2.3.3
  - libdeflate=1.23
  - libdrm=2.4.124
  - libedit=3.1.20250104
  - libegl=1.7.0
  - libexpat=2.7.0
  - libffi=3.4.6
  - libfreetype=2.13.3
  - libfreetype6=2.13.3
  - libgcc=15.1.0
  - libgcc-ng=15.1.0
  - libgl=1.7.0
  - libglib=2.84.1
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgomp=15.1.0
  - libhwloc=2.11.2
  - libiconv=1.18
  - libjpeg-turbo=3.1.0
  - liblapack=3.9.0
  - libllvm20=20.1.4
  - liblzma=5.8.1
  - libnsl=2.0.1
  - libntlm=1.8
  - libopengl=1.7.0
  - libpciaccess=0.18
  - libpng=1.6.47
  - libpq=17.5
  - libprotobuf=5.29.3
  - libsqlite=3.49.2
  - libstdcxx=15.1.0
  - libstdcxx-ng=15.1.0
  - libtiff=4.7.0
  - libtorch=2.6.0
  - libuuid=2.38.1
  - libuv=1.50.0
  - libwebp-base=1.5.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxkbcommon=1.9.2
  - libxml2=2.13.8
  - libxslt=1.1.39
  - libzlib=1.3.1
  - llvm-openmp=20.1.4
  - markupsafe=3.0.2
  - matplotlib-base=3.10.0
  - mkl=2024.2.2
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - munkres=1.1.4
  - ncurses=6.5
  - networkx=3.4.2
  - nptyping=2.5.0
  - numpy=1.26.4
  - openjpeg=2.5.3
  - openldap=2.6.9
  - openssl=3.5.0
  - optree=0.15.0
  - packaging=25.0
  - pcre2=10.44
  - pip=25.1.1
  - pixman=0.46.0
  - pthread-stubs=0.4
  - pybind11=2.13.6
  - pybind11-global=2.13.6
  - pyparsing=3.2.3
  - pyside6=6.9.0
  - python=3.10.17
  - python-dateutil=2.9.0.post0
  - python_abi=3.10
  - pytorch=2.6.0
  - qhull=2020.2
  - qt6-main=6.9.0
  - readline=8.2
  - setuptools=75.8.2
  - six=1.17.0
  - sleef=3.8
  - sympy=1.14.0
  - tbb=2021.13.0
  - tk=8.6.13
  - tornado=6.4.2
  - typing-extensions=4.13.2
  - typing_extensions=4.13.2
  - typish=1.9.3
  - tzdata=2025b
  - unicodedata2=16.0.0
  - wayland=1.23.1
  - wheel=0.45.1
  - xcb-util=0.4.1
  - xcb-util-cursor=0.1.5
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.1
  - xcb-util-renderutil=0.3.10
  - xcb-util-wm=0.4.2
  - xkeyboard-config=2.44
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxcomposite=0.4.6
  - xorg-libxcursor=1.2.3
  - xorg-libxdamage=1.1.6
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.1
  - xorg-libxi=1.8.2
  - xorg-libxrandr=1.5.4
  - xorg-libxrender=0.9.12
  - xorg-libxtst=1.2.5
  - xorg-libxxf86vm=1.1.6
  - zstd=1.5.7
  - pip:
      - bitarray==3.4.0
      - cffi==1.17.1
      - clingo==5.8.0
      - deepxube==0.1.5
      - imageio==2.37.0
      - janus-swi==1.5.2
      - kiwisolver==1.4.8
      - matplotlib==3.10.3
      - nvidia-cublas-cu12==12.6.4.1
      - nvidia-cuda-cupti-cu12==12.6.80
      - nvidia-cuda-nvrtc-cu12==12.6.77
      - nvidia-cuda-runtime-cu12==12.6.77
      - nvidia-cudnn-cu12==9.5.1.17
      - nvidia-cufft-cu12==11.3.0.4
      - nvidia-cufile-cu12==1.11.1.6
      - nvidia-curand-cu12==10.3.7.77
      - nvidia-cusolver-cu12==11.7.1.2
      - nvidia-cusparse-cu12==12.5.4.2
      - nvidia-cusparselt-cu12==0.6.3
      - nvidia-nccl-cu12==2.26.2
      - nvidia-nvjitlink-cu12==12.6.85
      - nvidia-nvtx-cu12==12.6.77
      - pillow==11.2.1
      - popper-ilp==4.2.0
      - pycparser==2.22
      - pyswip==0.3.2
      - python-sat==1.8.dev16
      - torch==2.7.0
      - triton==3.3.0
      - types-pillow==10.2.0.20240822
      - wget==3.2
